### ISSUE TITLE
XVotemap is not running!

### ISSUE THREAD

**Issue by ghost** [Hedius/xVotemap#1]
Hello @Hedius,

The plugin is not running correctly in the ProCon server.

I know the in-game commands

/# that will not do.

/v, !v that works.

/nextmap, !nextmap that works.

/votemap, !votemap that doesn't work.

enablevotemap that doesn't work.

disablevotemap that doesn't work.

can you tell me why that is.

Server is powered by Gportal.

Thanks. 

ProCon Setting.

![image](https://user-images.githubusercontent.com/37779629/208296893-1c4682d3-3b32-4223-a2fb-c51371e6d706.png)

**Comment by Hedius** [comment]
/ as the prefix works. Using that on our servers.

Votemap works on my servers.


Enable disable votemap required you the have a procon account with maplist permissions and a matching name.

**Comment by ghost** [comment]
Hello ok yes that worked very nicely. can you send me a picture of your settings?
